name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/cafe_1.png
  - assets/images/pngtreehabanero_bell_pepper_trinidad_moruga_145749601.png
  - assets/images/macro_shot_of_apaprika_pepper_16_removebg_preview_1.png
  - assets/images/cd_08040_e_5_b_5678536_ce_498_fec_removebg_preview_1.png
  - assets/images/bunch_raw_mushrooms_wooden_plate_1.png
  - assets/images/vertical_photo_green_lettuce_leaves_1.png
  - assets/images/d_3_abdca_d_65_f_4_d_64957_e_5_e_2_bf_45_eba_76_removebg_preview_1.png
  - assets/images/fresh_broccoli_vegetable_1.png
  - assets/images/chef_making_ok_sign_white_background_1.png
  - assets/vectors/icon_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/vectors/icon_10_x2.svg
  - assets/images/burger_1.png
  - assets/images/pngtree_pizza_9062008_removebg_preview_1.png
  - assets/images/a_63_e_81_acb_96424_ffab_5_removebg_preview_1.png
  - assets/images/menu_1.png
  - assets/images/pizza_1.png
  - assets/images/strawberry_cake_1.png
  - assets/vectors/icon_12_x2.svg
  - assets/vectors/icon_13_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/icon_1_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/wifi_x2.svg
  -  assets/images/strawberry_cake_1.png
  - assets/images/strawberry_cake_1.png
  - assets/images/burger_1.png
  - assets/images/pizza_1.png
  - assets/images/image_55.png
  - assets/images/menu_1.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/line_71_x2.svg
  - assets/vectors/interval_x2.svg
  - assets/vectors/icon_8_x2.svg
  - assets/vectors/ax_x2.svg
  - assets/vectors/icon_6_x2.svg
  - assets/vectors/group_17828_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/rectangle_4170_x2.svg
  - assets/vectors/group_167131_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/ellipse_42_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/images/dae_7998_e_4_ddfb_250_b_1646_b_3_bf_6290_c_62.png
  - assets/images/jgvc_2.png
  - assets/vectors/path_33918_x2.svg
  - assets/vectors/ellipse_139_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/rectangle_1051_x2.svg
  - assets/vectors/emojibanknote_with_dollar_sign_x2.svg
  - assets/vectors/path_339112_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/ellipse_140_x2.svg
  - assets/images/image_82.png
  - assets/images/image_85.png
  - assets/images/image_80.png
  - assets/vectors/group_178396_x2.svg
  - assets/vectors/group_1011_x2.svg
  - assets/vectors/path_33917_x2.svg
  - assets/vectors/path_3391_x2.svg
  - assets/vectors/rectangle_1053_x2.svg
  - assets/vectors/group_1015_x2.svg
  - assets/vectors/group_178391_x2.svg
  - assets/images/image_80.png
  - assets/images/image_85.png
  - assets/images/image_82.png
  - assets/vectors/path_33919_x2.svg
  - assets/vectors/group_178392_x2.svg
  - assets/vectors/group_101_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/group_1012_x2.svg
  - assets/vectors/path_33911_x2.svg
  - assets/vectors/rectangle_296_x2.svg
  - assets/vectors/rectangle_105_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/group_178395_x2.svg
  - assets/vectors/group_180711_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/path_33912_x2.svg
  - assets/images/rectangle_41091.png
  - assets/images/rectangle_4109.png
  - assets/images/rectangle_41092.png
  - assets/images/rectangle_41093.png
  - assets/vectors/path_233_x2.svg
  - assets/vectors/path_339111_x2.svg
  - assets/vectors/path_232_x2.svg
  - assets/vectors/path_231_x2.svg
  - assets/vectors/path_23_x2.svg
  - assets/images/restutrnt_profile_1.png
  - assets/vectors/group_x2.svg
  - assets/vectors/document_x2.svg
  - assets/vectors/profile_x2.svg
  - assets/vectors/setting_x2.svg
  - assets/vectors/wallet_x2.svg
  - assets/vectors/message_x2.svg
  - assets/vectors/iconly_bulk_helps_x2.svg
  - assets/vectors/group_18072_x2.svg
  - assets/images/image_80.png
  - assets/images/image_82.png
  - assets/images/image_85.png
  - assets/vectors/rectangle_1052_x2.svg
  - assets/vectors/path_33913_x2.svg
  - assets/vectors/group_178394_x2.svg
  - assets/vectors/path_339110_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/group_1017_x2.svg
  - assets/vectors/group_17839_x2.svg
  - assets/vectors/group_1016_x2.svg
  - assets/images/image_80.png
  - assets/images/image_82.png
  - assets/images/image_85.png
  - assets/vectors/group_178393_x2.svg
  - assets/vectors/group_1013_x2.svg
  - assets/vectors/group_1014_x2.svg
  - assets/vectors/group_178397_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/strawberry_cake_1.png
  - assets/images/burger_1.png
  - assets/images/menu_1.png
  - assets/images/image_55.png
  - assets/images/pizza_1.png
  - assets/vectors/ellipse_421_x2.svg
  - assets/vectors/icon_11_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/vectors/group_178281_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/line_7_x2.svg
  - assets/vectors/group_16713_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/images/image_27.png
  - assets/images/image_76.png
  - assets/images/image_35.png
  - assets/vectors/union_x2.svg
  - assets/vectors/path_33914_x2.svg
  - assets/vectors/union_2_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/images/image_82.png
  - assets/images/image_80.png
  - assets/images/image_13.png
  - assets/images/image_4.png
  - assets/vectors/path_33921_x2.svg
  - assets/vectors/icon_4_x2.svg
  - assets/vectors/path_33893_x2.svg
  - assets/vectors/path_33922_x2.svg
  - assets/vectors/path_33892_x2.svg
  - assets/vectors/path_33915_x2.svg
  - assets/vectors/group_18071_x2.svg
  - assets/vectors/path_3392_x2.svg
  - assets/vectors/path_33894_x2.svg
  - assets/images/image_79.png
  - assets/images/image_29.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/path_33895_x2.svg
  - assets/vectors/path_33891_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/path_3389_x2.svg
  - assets/vectors/path_33897_x2.svg
  - assets/vectors/path_33916_x2.svg
  - assets/vectors/path_33896_x2.svg



